### ISSUE TITLE
Sale ID Without Word "POS"

### ISSUE THREAD

**Issue by Ibnumarjan** [opensourcepos/opensourcepos#1012]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug
I would like to have Sale ID without word "POS". Now in the sales receipt it is showing as "POS 1", "POS 2"....,But We want just 6 digit continues number.

Can any one help please 

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Steps to reproduce the issue

**Comment by Ibnumarjan** [comment]
I would like to have Sale ID without word "POS". Now in the sales receipt it is showing as "POS 1", "POS 2"....,But We want just 6 digit continues number.

Can any one help please

**Comment by daN4cat** [comment]
This is not an easy change because POS as RECV and KIT are written in various places in the code.
This comes from the original design of the software and a change also implies supporting the conversion of old sales for people that has already existing databases.

**Comment by ikikika** [comment]
Hi, i hope it's not too late and i hope this does not violate any of ospos terms.

1. Go to application > controllers > Sales.php
2. look for this line `$data['sale_id'] = 'POS ' . $sale_id;`
3. remove the 'POS' or replace it with whatever you want.

Cheers.

**Comment by jadoux** [comment]
I have the same requirements, I am assuming that more fields are added in the code that require to be changed by now, I see multiple 'sale_id' lines in the same php, do we have to change them all now?

**Comment by kasunSL** [comment]
> I have the same requirements, I am assuming that more fields are added in the code that require to be changed by now, I see multiple 'sale_id' lines in the same php, do we have to change them all now?

 IT WORKES!!! i found 3 entries in line 996,793,679. after removing all the 'POS', it works like charm. thankyou @ikikika for heads-up

**Comment by kasunSL** [comment]
> Hi, i hope it's not too late and i hope this does not violate any of ospos terms.
> 
> 1. Go to application > controllers > Sales.php
> 2. look for this line `$data['sale_id'] = 'POS ' . $sale_id;`
> 3. if u just want the running number, remove  `'POS'.`. Dun forget to remove the DOT following 'POS'.
> 
> Cheers.

IT WORKES!!! i found 3 entries in line 996,793,679. after removing all the 'POS', it works like charm. thankyou @ikikika for heads-up

**Comment by Achterstraat** [comment]
I guess it's better to change KIT/POS to # for example cause.. ..the functions **is_valid_item_kit** and **is_valid_receipt** will always returning false!

**FROM**
../controllers/Sales.php
`$data['sale_id'] = 'POS ' . $sale_id;`
../models/Item_kit.php
`if(count($pieces) == 2 && preg_match('/(KIT)/i', $pieces[0]))`
../models/Sale.php
`if(count($pieces) == 2 && preg_match('/(POS)/i', $pieces[0]))`

TO
../controllers/Sales.php
`$data['sale_id'] = '#' . $sale_id;`
../models/Item_kit.php
`if(count($pieces) == 2 && preg_match('/(KIT|#)/i', $pieces[0]))`
../models/Sale.php
`if(count($pieces) == 2 && preg_match('/(POS|#)/i', $pieces[0]))`
