### ISSUE TITLE
[Epic] Credit Receivings

### ISSUE THREAD

**Issue by emi-silva** [opensourcepos/opensourcepos#2088]
## Context
In the organic store where I'm currently working, receivings aren't usually paid for immediately. Instead, they're paid on a _factura vencida_ basis, which means that, when the supplier brings new products to the store, she only gets paid for the products she had brought last time. So we need a way to pay for receivings on credit. Or, put in accounting words, we need an Accounts Payable functionality.

## Design
Given that, for this use case, the receiving of the products takes place in a different moment than the transfer of money, we need a way to differentiate these two actions. In order to do that, I propose the following sequentiality from the user's point of view:
1. The supplier brings new products to the store. The store owner goes to the Receivings module, registers the products, and chooses "Due" as a payment type. The supplier's balance increases.
2. The store owner wants to know how much she owes the supplier. She goes to the Reports module, choses "Accounting" and sees a list of suppliers and their balances. The bigger the balance, the more the supplier is owed.
3. When the payment is due, the store owner makes a bank transfer to the supplier. She then goes to the Expenses module and registers the payment she just made. The supplier's balance decreases.

## Implementation Steps
- [x] 1. In the Receivings module, add a new payment type called "Due", just like in the Sales module. This was implemented in #2080.
- [ ] 2. Modify the Expenses module so that its Supplier field is associated with actual suppliers in the database, i.e., add a foreign key from `ospos_expenses` to `ospos_suppliers` and display a dropdown list with the suppliers, just like in the Receivings module.
- [ ] 3. Create a new report called Accounting, where you can see a list of suppliers and their balances. Balances are calculated by subtracting expenses paid to each supplier, from the "Due" receivings associated to them. The more you owe them, the higher their balance.
- [ ] 4. Make it impossible to modify most fields of past expenses so that they become more legally binding, and generate expense receipts. This should be very similar to the "Daily Sales" functionality.

## Discussion
An early proposal and discussion of this improvement can be found in Pull Request #2080. Here are some highlights:

### Accounting in OSPOS
@jekkos [points out](https://github.com/opensourcepos/opensourcepos/pull/2080#discussion_r210785171) that there has been a lot of discussion on whether OSPOS should have accounting functionalities. Although I'm not familiar with that discussion, I have the belief that it should. Accounting is a basic need for any business and, at least in my experience, small businesses who benefit from OSPOS also need basic accounting functionalities very badly. I regard this improvement as a first step toward that goal.

### Purpose of the Expenses module
@jekkos [asks](https://github.com/opensourcepos/opensourcepos/pull/2080#discussion_r210783658) about the purpose of the Expenses module. In my view, the OSPOS user should be able to use this module to register all the expenses she makes in her business, so that she has all her accounting data in the same place, and at the end of the month she is able to export it to an Excel spreadsheet and create an Income Statement easily.

**Comment by izeblood** [comment]
This is what OSPOS needs...The 3.3 version must be a complete collaboration of all issue being raised and therefore 3.3 must use all these features...

**Comment by daN4cat** [comment]
We discussed how OSPOS is not an accounting system but a stock management tool.
I'm not sure what kind of progress will follow up.

**Comment by emi-silva** [comment]
Hi @jekkos, I'm still waiting for your review.

**Comment by jekkos** [comment]
Ok I did review the discussion with @daN4cat and I agree that it might not be appropriate to do any real 'accounting' module.

On the other hand now that we already have this 'expenses' module to me it seems not completely unreasonable to have basic reporting based on the data entered there. Also I know that @daN4cat opts not to have any 'suppliers' listed, but maybe we can just stick to adding an autocomplete for the persons table in that case, so at least we can do a data linkage there.

@daN4cat any objections if this we proceed then with this story?

**Comment by SteveIreland** [comment]
@emi-silva you are mistaken on multiple points.

A full featured international accounting system handling multiple regional rules is quite complex. I've been personally involved in the development of multiple software packages and can personally attest to that fact.  It's ludicrous to argue the opposite.

No one is  arguing that OSPOS includes some accounting functionality.  The point is that the useful reporting associated with OSPOS accounting is limited to operations.  I can generally be blamed for the expansion of OSPOS a tiny bit beyond just a POS system.  @jekkos and @daN4cat have been very gracious to allow expanding the functionality just enough to support a start-up service and repair business that requires POS for walk-in businesses.

A year or two ago I asked about adding an accounting component to OSPOS and was told that it was beyond the scope of OSPOS and that is totally understandable.  There isn't a full time development staff and if I have my heart attack next week then it will be the core team of part-time developers who are left with the mess.  They care about POS ... not accounting.

There is strong desire to improve OSPOS here and there.  I'm working on expanding the features in the taxing component.  Capturing payments on past due accounts is something I'd love to see added.  It, of course, would need to include a simple report of past due invoices.  It wouldn't be a full receivables system with statements, credit hold support, etc. but it is "just enough" that it can do the job yet still be maintainable.

Again, please don't dismiss the concerns of the architects here that are trying to keep OSPOS a package that can be maintained and supported by a small set of volunteer developers.

There is an open source accounting tool that has a different set of volunteer developers maintaining it called FrontOffice Accounting.  It is an ERP system that some have expressed an interesting in integrating with OSPOS.  It would be awesome if someone actually completed the integration.  I started it but it wasn't a priority for me and there was a problem that resulted in my dropping it. 

Having said all of the above I actually do have a project in the 4.0 queue to better manage inventory and a piece of that involves payables, but the scope will be limited to just what's needed to hopefully make it easier for OSPOS users to maintain prices - if not then it will never see the light of day.

**Comment by daN4cat** [comment]
@emi-silva first of all I didn't make any personal remark when I explained where OSPOS comes from and what has been added for what purpose.
So please refrain from making judgements on personal capabilities.

As an Sr Architect, who I am, I reason on separation of concerns and build systems that focus on being fully functioning in their purpose and scope but partitioned in different parts to avoid the old school monoliths.
I consider what we have, the maturity of it, the fragility and how easy is to maintain and expand.
Also I look at the front desk functionality, at the operational functionality and if there is any customer interaction.
OSPOS is not modular as it should be. Adding more functionality would require hacking stuff in touching here and there, increasing the cost of maintaining it.
Also the layering is not ideal, there is no clean separation between front end and business logic. We are at a mix of php, html, js/jQuery, bootstrap and etc. In views and views and controller have no clear interface and data format exchange based for instance on json. It's mixup.
There is no regression test harness to make sure changes don't break something else. Everytime somebody talks about approximation and tax schemas I feel the huge pain coming. I don't know how much time we spent on that because part is SQL and part is php calculations.

The database domain model is getting tidy up, but there is no dimensional view for reporting outside using temp tables.
That's why I always suggest to use an external tool to build the reports so even you understand what that implies.

OSPOS was started with something simple in mind and kept growing.
The focus was mainly front desk operations.
Back office was added recently and mainly for invoicing.

Everyone loves having the perfect do all solution, but it comes to a cost. And if not done properly could be a mess.
Hacking in "my piece of functionality" would compromise current functionality and what it could have been.

If we first switch to CodeIgniter modular support and then add more would be better.
Keeping functionality separated would allow scaling in an addon pattern.

Expenses and cash up was added for the only purpose of keeping track of the cash in the front desk drawer. Also to have a log journal for any cross check.

For my wife's business the accountancy and business plan is done using Google sheet, tracking invoices and payments in a timeline and feeding the business plan automatically to keep a  strategic view of the business in one page.

Also the people rota is a Google sheet visible to personnel to know when they need to work and post comments for changes.
In the background the hours are fed in another sheet used to calculate wages, which feed in automatically in the business plan.
Also all the buying plan is controlled to avoid killing the cash flow in 12 months time, because feeds in the same business plan view.

Different people see different sheets but only my wife and I see the business plan view distilled from all the other parts once converted in money units.

So don't come to me saying what you said, I'm far ahead of what you are even currently thinking.

When we explain to other people in my wife's business sector what we have and do they can't believe a small company manages the business in a strategic way like a big one. But that's our competitive advantage.

**Comment by daN4cat** [comment]
Having said all of that, we can see what is sensible in what you want to achieve.

If supplier view can have a way to discriminate between goods, services or some category than we can organise them for all purposes. Maybe having in expenses a means to select the category.... don't some wild thinking here.

Also would it make sense for you to take the ospos framework and strip it out of all the register and receiving stuff and just build back office functionality running it as a separate app?
Something like oserp?
You can interface the same database and maybe we can move the back office feature to that app.
Again some wild thinking here...

Open for discussion

**Comment by daN4cat** [comment]
For sure we would be happy to host any oserp code in this githun space.

**Comment by daN4cat** [comment]
Guys, I can't stop you to do what you want, please go ahead if you feel you want more and have the energy to implement it. The current master version is enough for my needs.

**Comment by SteveIreland** [comment]
Oh no ... he's released the demons.

**Comment by daN4cat** [comment]
@WebShells or you meant something else?

**Comment by daN4cat** [comment]
BTW, for purely accounting purposes I would consider this open source app: http://webzash.org/
I had a look a couple of years ago and it looks a nice tool, we should probably integrate with that.

**Comment by WebShells** [comment]
@daN4cat webzash looks more simple and less complicated than what i've checked before... And indeed it fits OSPOS more than FrontAccounting, based on bootstrap... @SteveIreland check that!

**Comment by WebShells** [comment]
You're right regarding whats mentioned of work and improvements, and for sure we wont reach the level they reached since it was their core work since started... Maybe simple integration to allow exporting data from ospos to another solution launched through our modules list, might ease up the process for the user and finishes the accounting section...

**Comment by SteveIreland** [comment]
I checked out the features of webzash and it looks to be primarily a general ledger app which would be nice for those accounting oriented folks.  We would then need to feed the beast by adding in all of the "missing" back office features such as payables and receivables.

I installed frontaccounting for a client and they never used it.  It was too complicated for them and compared to OSPOS it was kludgy.  Also, it seemed that as soon as I had one employee vaguely familiar with it they quit or were fired for whatever reason and replaced by another person.   I gave up on it.  They were more comfortable using a spreadsheet to track what interested them.  So because of its simplicity Webzash seems promising.

If we had the basic features for tracking and reporting payables and receivables and all of that fed into Webzash for management and government reporting then I think OSPOS would be close to approaching everything a a small business needs.

**Comment by emi-silva** [comment]
I apologize, @daN4cat. I didn't intend to offend you.

What @SteveIreland says makes a lot of sense to me. Irrespective of the decision to integrate OSPOS with an accounting tool, we still need to be able to track four things:

1. When you owe money to a supplier (accounts payable)
2. When a customer owes you money (accounts receivable)
3. When you pay a supplier (cash flow out)
4. When a customer pays you (cash flow in)

As soon as we have that, an accounting tool could be able to generate a (partial) balance sheet.
I created this Epic precisely with the intent of implementing 1 and 3. I can modify my initial proposal to add supplier categories, as @daN4cat suggests, in order to differentiate what he calls capex and opex.

If I did that, would you guys accept my proposal?

**Comment by odiea** [comment]
Once you get your branch current with master and add your features I would like to see how it works.

**Comment by daN4cat** [comment]
@emi-silva it's fine to add what you suggested and it will mainly be money in & out related to stock, plus the utility bills and similar part of the running cost.
Yes, make a distinction between suppliers selling goods for reselling and suppliers being just a running cost.

One day we will get the purchasing life cycle management that will need to fit the accounts payable part and cash flow out. So be aligned with Steve on that.

Also we should output everything to be ingested by Webzash to have a complete accountancy view. I'll check how that could take place.

**Comment by emi-silva** [comment]
I updated the first post of this Issue to reflect the latest discussion. I'm going to create a nullable foreign key from expenses to suppliers, as well as a category dropdown in the New Expense form. What should the names of the categories be? I propose Operating Expenses vs. Cost of Goods Sold. Check out their definition [here](https://www.investopedia.com/ask/answers/101314/what-are-differences-between-operating-expenses-and-cost-goods-sold-cogs.asp). Another proposal, less formal but maybe more understandable, could be Cost Suppliers vs. Main Suppliers.

Today I'm leaving for a trip and will come back in a few days.

**Comment by daN4cat** [comment]
@emi-silva our accountant refers to it as Cost Of Sales (Opening Stock + Purchases - Closing Stock). It's capital expenditure that generates a profit, but all of that is the accountancy definition.

Maybe instead of Cost & Main could be Cost & Goods.

Another confusion about Suppliers is the mixup Brand, Supplier/Manufacturer company and Agency.
Items should be more related to brands (e.g. Pampers is a brand, but the supplier/manufacturer is Procter & Gamble UK and maybe there is a regional Agent managing the sale channel).

I wonder if it's the time to get that right but could be a bit of a pain to change that.

I'm saying that because when it comes to accountancy you may want the breakdown itemising costs against the company not the brand, where on the Stock management side you may want to have a Brands view.

**Comment by emi-silva** [comment]
I will go for Cost Suppliers and Goods Suppliers. I updated the description of this issue to reflect what I'm gonna do. I'll start with the second implementation step. Any comments welcome.

**Comment by WebShells** [comment]
Thanks for your contribution and time @Emi-Silva

**Comment by jekkos** [comment]
Just had some second thoughts on this addition. Wouldn't it make sense to be able to link an expense to a receiving_id ? In this case you then enter the invoice amount for the receiving which can include extra discounts on the whole order.


It would certainly be a useful addition for me as currently there is no easy way to keep track of costs linked to a receiving

**Comment by jekkos** [comment]
Also I wonder whether it still makes sense then to link to a supplier as well (as this one can be retrieved from the receiving itself).

**Comment by mckaygerhard** [comment]
theres son details important, the amount are still editable.. tha are not good in fiscal terms..that are totally wrong.. i think as many here are pointed this implementatio are too basic to take it as feature...

**Comment by HamidCh** [comment]
So are we still up for adding CREDIT PAYMENTS module?
